### ISSUE TITLE
400 Bad Request when download

### ISSUE THREAD

**Issue by mashirozx** [Chevereto/docker-builder#51]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/16148054/219535864-62120088-4e21-47c7-8cdd-f93ce6e0d86f.png">

**Comment by mashirozx** [comment]
Both with/without input returns this.

IDC: Oracle Integration Cloud (OIC)
IPDR: 138.2.0.0/19

**Comment by mashirozx** [comment]
Both with/without license input returns this.

IDC: Oracle Integration Cloud (OIC)
CIDR: 138.2.0.0/16
NetRange: 138.2.0.0 - 138.2.255.255

**Comment by rodber** [comment]
When accessing to the API download and not providing the key, the system redirects (http redirect) to GitHub download link.

HTTP 4XX namespace is for client error, you should check how your machine is connecting to internet.
