### ISSUE TITLE
400 Bad Request when download

### ISSUE THREAD

**Issue by mashirozx** [Chevereto/docker-builder#53]
![Screenshot_2023-02-17-18-26-09-998_com sonelli juicessh-edit](https://user-images.githubusercontent.com/16148054/219619106-275468cc-ec39-48ed-9426-ad5e782725ec.jpg)

seems that your server returns 400

#51

**Comment by rodber** [comment]
The make target command is just a wrapper for curl, you are running in circles. You need to test from another machine.

Please do not bomb me with issues, use the discussion where this is being discussed: https://github.com/chevereto/docker/discussions/52
